In [1]:
from utils import AMAEConfig
from model import AudioMAE
import librosa
import os
import torch
from torchinfo import summary


In [2]:
test_cfg = AMAEConfig(cfg_path=r'E:\project\python\Audio_MAE_Base_ST\config\auto_encoder.yaml')
test_m = AudioMAE(test_cfg)
test_f = os.path.join('datas', 'test', 'test_10s.wav')
signal, _ = librosa.load(test_f, sr=32000, mono=True)
model_input = torch.Tensor(signal).unsqueeze(0)

In [3]:
summary(test_m, input_size=(4, 320000), depth=5, col_names=("input_size", "output_size", "num_params", "trainable", "kernel_size"))

Layer (type:depth-idx)                                  Input Shape               Output Shape              Param #                   Trainable                 Kernel Shape
AudioMAE                                                [4, 320000]               [4, 1, 1024, 64]          --                        Partial                   --
├─STEncoder: 1-1                                        [4, 320000]               --                        --                        Partial                   --
│    └─Spectrogram: 2-1                                 [4, 320000]               [4, 1, 1001, 513]         --                        False                     --
│    │    └─STFT: 3-1                                   --                        --                        --                        False                     --
│    │    │    └─Conv1d: 4-1                            [4, 1, 321024]            [4, 513, 1001]            (525,312)                 False                     [1024]
│    │  

In [1]:
from dataset import FinetuneAS2k
from utils import AMAEConfig

In [2]:
ft_cfg = AMAEConfig(cfg_path=r'config\finetune_AS20k.yaml')
ft_dataset = FinetuneAS2k(ft_cfg)

In [3]:
ft_dataset[0]

(tensor([[-7.1173, -5.4450, -4.7622,  ..., -4.8091, -5.5432, -6.4559],
         [-5.7448, -5.2049, -5.0482,  ..., -4.1698, -5.6299, -6.4060],
         [-6.5856, -5.4705, -5.3254,  ..., -5.0102, -5.1550, -6.5707],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]),
 tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [104]:
import pandas as pd
import numpy as np

In [107]:
temp_df = pd.DataFrame(data=None, columns=["file", "type", "label"])
len(temp_df.index)

0

In [108]:
temp_df.loc[len(temp_df.index)] = [os.path.join('datas', 'test', 'test_10s.wav'), 'train', -1]
temp_df.loc[len(temp_df.index)] = [os.path.join('datas', 'test', 'test_30s.wav'), 'eval', -1]

In [109]:
temp_df.reset_index(drop=True, inplace=True)
temp_df

file   type  label
0  datas\test\test_10s.wav  train     -1
1  datas\test\test_30s.wav   eval     -1

In [110]:
temp_df.to_csv(os.path.join('workspace', 'test.csv'))

In [111]:
rdf = pd.read_csv(os.path.join('workspace', 'test.csv'), index_col=0)

In [112]:
rdf

file   type  label
0  datas\test\test_10s.wav  train     -1
1  datas\test\test_30s.wav   eval     -1

In [113]:
list(rdf['file'])

['datas\\test\\test_10s.wav', 'datas\\test\\test_30s.wav']

In [119]:
list(rdf[rdf['type'] == 'train']['file'])

['datas\\test\\test_10s.wav']

In [24]:
a = 'aabccd.hdf5'
a

'aabccd.hdf5'

In [25]:
str_list = list(a)
str_list

['a', 'a', 'b', 'c', 'c', 'd', '.', 'h', 'd', 'f', '5']

In [29]:
n = 5
str_list.insert(-5, f'_{n}')
str_list

['a', 'a', 'b', 'c', 'c', 'd', '_0', '_5', '_5', '.', 'h', 'd', 'f', '5']

In [7]:
def get_hdf5_handler(base_name):
    suffix = base_name.split('.')[-1]
    prefix = base_name[:-len(suffix) - 1]
    hdf5_files = [prefix + f'_{i}.' + suffix for i in range(2)]
    h5f_l = []
    return h5f_l

result = get_hdf5_handler('test.hdf5')
result

['test_0.hdf5', 'test_1.hdf5', 'test_2.hdf5', 'test_3.hdf5', 'test_4.hdf5']

In [3]:
result = get_hdf5_handler('test.hdf5')
result

test.hdf5
['t', 'e', 's', 't', '.', 'h', 'd', 'f', '5']
[['t', 'e', 's', 't', '.', 'h', 'd', 'f', '5'], ['t', 'e', 's', 't', '.', 'h', 'd', 'f', '5']]


[['t', 'e', 's', 't', '_0', '.', 'h', 'd', 'f', '5'],
 ['t', 'e', 's', 't', '_0', '_1', '.', 'h', 'd', 'f', '5']]

In [28]:
ll = [round(i * 119 / 10) for i in range(1, 1+10)]
ll

[12, 24, 36, 48, 60, 71, 83, 95, 107, 119]

In [22]:
import bisect
bisect.bisect_left(ll, 119)

10

In [59]:
import os
import torch
import librosa
import torchaudio
test_f = os.path.join('datas', 'test', 'test_5s.wav')

In [67]:
signal, sr = torchaudio.load(test_f)
signal_tensor = torchaudio.functional.resample(signal, sr, 32000)
signal_tensor = signal_tensor[:, :16000]
signal_tensor.mean()

tensor(-8.6682e-06)

In [70]:
fbank1 = torchaudio.compliance.kaldi.fbank(signal_tensor, sample_frequency=32000, num_mel_bins=64, frame_length=25, frame_shift=10, use_energy=False, htk_compat=True, window_type='hanning')
fbank1.shape, fbank1

(torch.Size([498, 64]),
 tensor([[-9.3886, -7.8770, -5.4048,  ...,  2.5769,  5.2955,  2.8710],
         [-8.7952, -7.8567, -6.9791,  ...,  3.4606,  5.4970,  2.7016],
         [-8.7187, -6.5805, -5.2349,  ...,  3.6090,  5.7197,  3.2470],
         ...,
         [-8.4016, -6.8130, -4.8061,  ...,  2.1012,  5.5413,  4.0948],
         [-8.6447, -6.5375, -4.9988,  ...,  2.1592,  5.6082,  4.2566],
         [-8.9351, -7.1739, -4.5902,  ...,  2.0951,  5.7093,  4.4088]]))

In [72]:
fbank2_m = torchaudio.transforms.MelSpectrogram(
    sample_rate=32000,
    n_fft = 800,
    hop_length = 320,
    f_min = 20.0,
    n_mels = 64,
)
fbank2 = fbank2_m(signal_tensor)
log_offset = 1e-6
fbank2 = torch.log(fbank2 + log_offset).permute(0, 2, 1).squeeze(0)
fbank2.shape, fbank2

(torch.Size([501, 64]),
 tensor([[-0.8197, -0.8853,  1.3534,  ...,  1.1577,  4.2555,  1.5151],
         [-2.7766, -1.6788,  1.1588,  ...,  0.9371,  3.7480,  1.3173],
         [-2.3074, -1.4341, -0.7969,  ...,  1.6858,  3.8068,  1.0996],
         ...,
         [-2.0937, -1.6511,  1.2522,  ...,  0.5090,  4.1544,  2.8605],
         [-2.5462, -1.1531,  1.5938,  ...,  1.1356,  4.0340,  2.6191],
         [-2.2207,  0.0892,  1.4528,  ...,  0.9726,  4.0239,  2.6166]]))

In [79]:
from torchlibrosa.stft import Spectrogram, LogmelFilterBank
spe_m = Spectrogram(n_fft=800, hop_length=320, win_length=800)
fbank3_m = LogmelFilterBank(sr=32000, n_fft=800, n_mels=64, fmin=20., top_db=None)
fbank3 = spe_m(signal_tensor)
fbank3 = fbank3_m(fbank3).squeeze(0).squeeze(0)
fbank3.shape, fbank3

(torch.Size([501, 64]),
 tensor([[-18.8689,  -9.6641,  -6.9690,  ..., -24.2087, -11.8399, -15.9438],
         [-24.2771, -10.6027,  -0.6918,  ..., -23.9369, -14.0355, -17.8179],
         [-22.7095, -19.2821,  -7.9552,  ..., -20.7821, -13.5998, -17.9113],
         ...,
         [-22.9208, -10.1186,  -0.4437,  ..., -24.5749, -12.5462, -13.9350],
         [-22.3521,  -8.7371,  -3.5879,  ..., -24.3663, -12.9280, -14.7525],
         [-17.8741,  -9.8546, -11.3344,  ..., -23.8807, -12.9823, -14.8048]]))

In [86]:
import numpy as np
def _pre_process(waveform):
    waveform = waveform - waveform.mean()
    idx = np.random.randint(len(waveform))
    rolled_waveform = np.roll(waveform, idx)
    mag = np.random.beta(10, 10) + 0.5
    waveform = rolled_waveform * mag

    return torch.Tensor(waveform)

In [88]:
waveform, _ = librosa.load(test_f, sr=32000)
# waveform = _pre_process(waveform)
type(waveform), waveform.shape

(numpy.ndarray, (160000,))

In [1]:
from utils import AMAEConfig
cfg = AMAEConfig(cfg_path='config/pretrain.yaml')

In [2]:
print(cfg)

AMAEConfig
cfg_path: config/pretrain.yaml
sample_rate: 32000
frame_length: 25
frame_shift: 10
mel_bins: 64
spec_size: 256
patch_size: 4
embed_dim: 96
window_size: 8
latent_channel: 32
extra_downsample_ratio: 1
num_classes: 0
absolute_position_embedding: False
EC_mlp_ratio: 4
EC_num_head: [4, 8, 16, 32]
EC_depth: [2, 2, 6, 2]
EC_attn_norm: True
EC_patch_norm: True
EC_qkv_bias: True
EC_drop_rate: 0.0
EC_attn_drop_rate: 0.0
EC_drop_path_rate: 0.1
DC_num_head: [32, 16, 8, 4]
DC_depth: [2, 6, 2, 2]
DC_mlp_ratio: 4.0
DC_drop_rate: 0.0
DC_attn_drop_rate: 0.0
DC_drop_path_rate: 0.1
DC_attn_norm: True
DC_patch_norm: True
DC_qkv_bias: True
h5df_write: False
pre_training: True
load_encoder: False
load_decoder: False
roll_mag_aug: True
mask_ratio: 0.6
norm_pix_loss: True
restore_mask_only: True
batch_size: 64
learning_rate: 0.001
max_epoch: 100
lr_scheduler: [0.02, 0.05, 0.1]
lr_scheduler_epoch: [4, 5, 6]
data_csv: workspace\datas.csv
hdf5_file: workspace\dataset_pretrain.hdf5
encoder_ckpt: worksp

AMAEConfig(cfg_path='config/pretrain.yaml', data_csv='workspace\\datas.csv', hdf5_file='workspace\\dataset_pretrain.hdf5', encoder_ckpt='workspace\\2024-06-15_21-16-26\\encoder_R1_E1.pth', decoder_ckpt='workspace\\2024-06-15_21-16-26\\decoder_R1_E1.pth', workspace='workspace', sample_rate=32000, frame_length=25, frame_shift=10, mel_bins=64, h5df_write=False, pre_training=True, load_encoder=False, load_decoder=False, roll_mag_aug=True, mask_ratio=0.6, norm_pix_loss=True, restore_mask_only=True, batch_size=64, learning_rate=0.001, max_epoch=100, lr_scheduler=[0.02, 0.05, 0.1], lr_scheduler_epoch=[4, 5, 6], extra_downsample_ratio=1, num_classes=0, embed_dim=96, patch_size=4, window_size=8, spec_size=256, latent_channel=32, absolute_position_embedding=False, EC_attn_norm=True, EC_patch_norm=True, EC_qkv_bias=True, EC_mlp_ratio=4, EC_num_head=[4, 8, 16, 32], EC_depth=[2, 2, 6, 2], EC_drop_rate=0.0, EC_attn_drop_rate=0.0, EC_drop_path_rate=0.1, DC_num_head=[32, 16, 8, 4], DC_depth=[2, 6, 2, 